#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDProyecto")]
	public partial class Conexion : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAerolinea(Aerolinea instance);
    partial void UpdateAerolinea(Aerolinea instance);
    partial void DeleteAerolinea(Aerolinea instance);
    partial void InsertAsiento(Asiento instance);
    partial void UpdateAsiento(Asiento instance);
    partial void DeleteAsiento(Asiento instance);
    partial void InsertAvion(Avion instance);
    partial void UpdateAvion(Avion instance);
    partial void DeleteAvion(Avion instance);
    partial void InsertBoleto(Boleto instance);
    partial void UpdateBoleto(Boleto instance);
    partial void DeleteBoleto(Boleto instance);
    partial void InsertRol(Rol instance);
    partial void UpdateRol(Rol instance);
    partial void DeleteRol(Rol instance);
    partial void InsertTipoAsiento(TipoAsiento instance);
    partial void UpdateTipoAsiento(TipoAsiento instance);
    partial void DeleteTipoAsiento(TipoAsiento instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertVuelo(Vuelo instance);
    partial void UpdateVuelo(Vuelo instance);
    partial void DeleteVuelo(Vuelo instance);
    #endregion
		
		public Conexion() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDProyectoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Conexion(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Conexion(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Conexion(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Conexion(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Aerolinea> Aerolinea
		{
			get
			{
				return this.GetTable<Aerolinea>();
			}
		}
		
		public System.Data.Linq.Table<Asiento> Asiento
		{
			get
			{
				return this.GetTable<Asiento>();
			}
		}
		
		public System.Data.Linq.Table<Avion> Avion
		{
			get
			{
				return this.GetTable<Avion>();
			}
		}
		
		public System.Data.Linq.Table<Boleto> Boleto
		{
			get
			{
				return this.GetTable<Boleto>();
			}
		}
		
		public System.Data.Linq.Table<Rol> Rol
		{
			get
			{
				return this.GetTable<Rol>();
			}
		}
		
		public System.Data.Linq.Table<TipoAsiento> TipoAsiento
		{
			get
			{
				return this.GetTable<TipoAsiento>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Vuelo> Vuelo
		{
			get
			{
				return this.GetTable<Vuelo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aerolinea")]
	public partial class Aerolinea : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idAerolinea;
		
		private string _nombre;
		
		private System.Nullable<decimal> _precio;
		
		private EntitySet<Avion> _Avion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidAerolineaChanging(int value);
    partial void OnidAerolineaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    #endregion
		
		public Aerolinea()
		{
			this._Avion = new EntitySet<Avion>(new Action<Avion>(this.attach_Avion), new Action<Avion>(this.detach_Avion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAerolinea", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idAerolinea
		{
			get
			{
				return this._idAerolinea;
			}
			set
			{
				if ((this._idAerolinea != value))
				{
					this.OnidAerolineaChanging(value);
					this.SendPropertyChanging();
					this._idAerolinea = value;
					this.SendPropertyChanged("idAerolinea");
					this.OnidAerolineaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(128)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aerolinea_Avion", Storage="_Avion", ThisKey="idAerolinea", OtherKey="idAerolinea")]
		public EntitySet<Avion> Avion
		{
			get
			{
				return this._Avion;
			}
			set
			{
				this._Avion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Avion(Avion entity)
		{
			this.SendPropertyChanging();
			entity.Aerolinea = this;
		}
		
		private void detach_Avion(Avion entity)
		{
			this.SendPropertyChanging();
			entity.Aerolinea = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asiento")]
	public partial class Asiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idAsiento;
		
		private string _numeroAsiento;
		
		private string _estado;
		
		private System.Nullable<decimal> _precio;
		
		private System.Nullable<int> _idTipoAsiento;
		
		private System.Nullable<int> _idAvion;
		
		private EntitySet<Boleto> _Boleto;
		
		private EntityRef<Avion> _Avion;
		
		private EntityRef<TipoAsiento> _TipoAsiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidAsientoChanging(int value);
    partial void OnidAsientoChanged();
    partial void OnnumeroAsientoChanging(string value);
    partial void OnnumeroAsientoChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OnidTipoAsientoChanging(System.Nullable<int> value);
    partial void OnidTipoAsientoChanged();
    partial void OnidAvionChanging(System.Nullable<int> value);
    partial void OnidAvionChanged();
    #endregion
		
		public Asiento()
		{
			this._Boleto = new EntitySet<Boleto>(new Action<Boleto>(this.attach_Boleto), new Action<Boleto>(this.detach_Boleto));
			this._Avion = default(EntityRef<Avion>);
			this._TipoAsiento = default(EntityRef<TipoAsiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAsiento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idAsiento
		{
			get
			{
				return this._idAsiento;
			}
			set
			{
				if ((this._idAsiento != value))
				{
					this.OnidAsientoChanging(value);
					this.SendPropertyChanging();
					this._idAsiento = value;
					this.SendPropertyChanged("idAsiento");
					this.OnidAsientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroAsiento", DbType="NVarChar(128)")]
		public string numeroAsiento
		{
			get
			{
				return this._numeroAsiento;
			}
			set
			{
				if ((this._numeroAsiento != value))
				{
					this.OnnumeroAsientoChanging(value);
					this.SendPropertyChanging();
					this._numeroAsiento = value;
					this.SendPropertyChanged("numeroAsiento");
					this.OnnumeroAsientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(128)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoAsiento", DbType="Int")]
		public System.Nullable<int> idTipoAsiento
		{
			get
			{
				return this._idTipoAsiento;
			}
			set
			{
				if ((this._idTipoAsiento != value))
				{
					if (this._TipoAsiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoAsientoChanging(value);
					this.SendPropertyChanging();
					this._idTipoAsiento = value;
					this.SendPropertyChanged("idTipoAsiento");
					this.OnidTipoAsientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAvion", DbType="Int")]
		public System.Nullable<int> idAvion
		{
			get
			{
				return this._idAvion;
			}
			set
			{
				if ((this._idAvion != value))
				{
					if (this._Avion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidAvionChanging(value);
					this.SendPropertyChanging();
					this._idAvion = value;
					this.SendPropertyChanged("idAvion");
					this.OnidAvionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asiento_Boleto", Storage="_Boleto", ThisKey="idAsiento", OtherKey="idAsiento")]
		public EntitySet<Boleto> Boleto
		{
			get
			{
				return this._Boleto;
			}
			set
			{
				this._Boleto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avion_Asiento", Storage="_Avion", ThisKey="idAvion", OtherKey="idAvion", IsForeignKey=true)]
		public Avion Avion
		{
			get
			{
				return this._Avion.Entity;
			}
			set
			{
				Avion previousValue = this._Avion.Entity;
				if (((previousValue != value) 
							|| (this._Avion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Avion.Entity = null;
						previousValue.Asiento.Remove(this);
					}
					this._Avion.Entity = value;
					if ((value != null))
					{
						value.Asiento.Add(this);
						this._idAvion = value.idAvion;
					}
					else
					{
						this._idAvion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Avion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoAsiento_Asiento", Storage="_TipoAsiento", ThisKey="idTipoAsiento", OtherKey="idTipoAsiento", IsForeignKey=true)]
		public TipoAsiento TipoAsiento
		{
			get
			{
				return this._TipoAsiento.Entity;
			}
			set
			{
				TipoAsiento previousValue = this._TipoAsiento.Entity;
				if (((previousValue != value) 
							|| (this._TipoAsiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoAsiento.Entity = null;
						previousValue.Asiento.Remove(this);
					}
					this._TipoAsiento.Entity = value;
					if ((value != null))
					{
						value.Asiento.Add(this);
						this._idTipoAsiento = value.idTipoAsiento;
					}
					else
					{
						this._idTipoAsiento = default(Nullable<int>);
					}
					this.SendPropertyChanged("TipoAsiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boleto(Boleto entity)
		{
			this.SendPropertyChanging();
			entity.Asiento = this;
		}
		
		private void detach_Boleto(Boleto entity)
		{
			this.SendPropertyChanging();
			entity.Asiento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Avion")]
	public partial class Avion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idAvion;
		
		private string _modelo;
		
		private System.Nullable<int> _idAerolinea;
		
		private EntitySet<Asiento> _Asiento;
		
		private EntitySet<Vuelo> _Vuelo;
		
		private EntityRef<Aerolinea> _Aerolinea;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidAvionChanging(int value);
    partial void OnidAvionChanged();
    partial void OnmodeloChanging(string value);
    partial void OnmodeloChanged();
    partial void OnidAerolineaChanging(System.Nullable<int> value);
    partial void OnidAerolineaChanged();
    #endregion
		
		public Avion()
		{
			this._Asiento = new EntitySet<Asiento>(new Action<Asiento>(this.attach_Asiento), new Action<Asiento>(this.detach_Asiento));
			this._Vuelo = new EntitySet<Vuelo>(new Action<Vuelo>(this.attach_Vuelo), new Action<Vuelo>(this.detach_Vuelo));
			this._Aerolinea = default(EntityRef<Aerolinea>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAvion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idAvion
		{
			get
			{
				return this._idAvion;
			}
			set
			{
				if ((this._idAvion != value))
				{
					this.OnidAvionChanging(value);
					this.SendPropertyChanging();
					this._idAvion = value;
					this.SendPropertyChanged("idAvion");
					this.OnidAvionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="NVarChar(128)")]
		public string modelo
		{
			get
			{
				return this._modelo;
			}
			set
			{
				if ((this._modelo != value))
				{
					this.OnmodeloChanging(value);
					this.SendPropertyChanging();
					this._modelo = value;
					this.SendPropertyChanged("modelo");
					this.OnmodeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAerolinea", DbType="Int")]
		public System.Nullable<int> idAerolinea
		{
			get
			{
				return this._idAerolinea;
			}
			set
			{
				if ((this._idAerolinea != value))
				{
					if (this._Aerolinea.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidAerolineaChanging(value);
					this.SendPropertyChanging();
					this._idAerolinea = value;
					this.SendPropertyChanged("idAerolinea");
					this.OnidAerolineaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avion_Asiento", Storage="_Asiento", ThisKey="idAvion", OtherKey="idAvion")]
		public EntitySet<Asiento> Asiento
		{
			get
			{
				return this._Asiento;
			}
			set
			{
				this._Asiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avion_Vuelo", Storage="_Vuelo", ThisKey="idAvion", OtherKey="idAvion")]
		public EntitySet<Vuelo> Vuelo
		{
			get
			{
				return this._Vuelo;
			}
			set
			{
				this._Vuelo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aerolinea_Avion", Storage="_Aerolinea", ThisKey="idAerolinea", OtherKey="idAerolinea", IsForeignKey=true)]
		public Aerolinea Aerolinea
		{
			get
			{
				return this._Aerolinea.Entity;
			}
			set
			{
				Aerolinea previousValue = this._Aerolinea.Entity;
				if (((previousValue != value) 
							|| (this._Aerolinea.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aerolinea.Entity = null;
						previousValue.Avion.Remove(this);
					}
					this._Aerolinea.Entity = value;
					if ((value != null))
					{
						value.Avion.Add(this);
						this._idAerolinea = value.idAerolinea;
					}
					else
					{
						this._idAerolinea = default(Nullable<int>);
					}
					this.SendPropertyChanged("Aerolinea");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asiento(Asiento entity)
		{
			this.SendPropertyChanging();
			entity.Avion = this;
		}
		
		private void detach_Asiento(Asiento entity)
		{
			this.SendPropertyChanging();
			entity.Avion = null;
		}
		
		private void attach_Vuelo(Vuelo entity)
		{
			this.SendPropertyChanging();
			entity.Avion = this;
		}
		
		private void detach_Vuelo(Vuelo entity)
		{
			this.SendPropertyChanging();
			entity.Avion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Boleto")]
	public partial class Boleto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idBoleto;
		
		private string _fecha;
		
		private System.Nullable<decimal> _precio;
		
		private string _estado;
		
		private string _nombre;
		
		private string _apellido;
		
		private System.Nullable<int> _edad;
		
		private string _correo;
		
		private string _codigo;
		
		private System.Nullable<int> _idVuelo;
		
		private System.Nullable<int> _idAsiento;
		
		private EntityRef<Asiento> _Asiento;
		
		private EntityRef<Vuelo> _Vuelo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBoletoChanging(int value);
    partial void OnidBoletoChanged();
    partial void OnfechaChanging(string value);
    partial void OnfechaChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnedadChanging(System.Nullable<int> value);
    partial void OnedadChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnidVueloChanging(System.Nullable<int> value);
    partial void OnidVueloChanged();
    partial void OnidAsientoChanging(System.Nullable<int> value);
    partial void OnidAsientoChanged();
    #endregion
		
		public Boleto()
		{
			this._Asiento = default(EntityRef<Asiento>);
			this._Vuelo = default(EntityRef<Vuelo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBoleto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idBoleto
		{
			get
			{
				return this._idBoleto;
			}
			set
			{
				if ((this._idBoleto != value))
				{
					this.OnidBoletoChanging(value);
					this.SendPropertyChanging();
					this._idBoleto = value;
					this.SendPropertyChanged("idBoleto");
					this.OnidBoletoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="NVarChar(128)")]
		public string fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(128)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(128)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="NVarChar(128)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="Int")]
		public System.Nullable<int> edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(128)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="NVarChar(256)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVuelo", DbType="Int")]
		public System.Nullable<int> idVuelo
		{
			get
			{
				return this._idVuelo;
			}
			set
			{
				if ((this._idVuelo != value))
				{
					if (this._Vuelo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidVueloChanging(value);
					this.SendPropertyChanging();
					this._idVuelo = value;
					this.SendPropertyChanged("idVuelo");
					this.OnidVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAsiento", DbType="Int")]
		public System.Nullable<int> idAsiento
		{
			get
			{
				return this._idAsiento;
			}
			set
			{
				if ((this._idAsiento != value))
				{
					if (this._Asiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidAsientoChanging(value);
					this.SendPropertyChanging();
					this._idAsiento = value;
					this.SendPropertyChanged("idAsiento");
					this.OnidAsientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asiento_Boleto", Storage="_Asiento", ThisKey="idAsiento", OtherKey="idAsiento", IsForeignKey=true)]
		public Asiento Asiento
		{
			get
			{
				return this._Asiento.Entity;
			}
			set
			{
				Asiento previousValue = this._Asiento.Entity;
				if (((previousValue != value) 
							|| (this._Asiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Asiento.Entity = null;
						previousValue.Boleto.Remove(this);
					}
					this._Asiento.Entity = value;
					if ((value != null))
					{
						value.Boleto.Add(this);
						this._idAsiento = value.idAsiento;
					}
					else
					{
						this._idAsiento = default(Nullable<int>);
					}
					this.SendPropertyChanged("Asiento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vuelo_Boleto", Storage="_Vuelo", ThisKey="idVuelo", OtherKey="idVuelo", IsForeignKey=true)]
		public Vuelo Vuelo
		{
			get
			{
				return this._Vuelo.Entity;
			}
			set
			{
				Vuelo previousValue = this._Vuelo.Entity;
				if (((previousValue != value) 
							|| (this._Vuelo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vuelo.Entity = null;
						previousValue.Boleto.Remove(this);
					}
					this._Vuelo.Entity = value;
					if ((value != null))
					{
						value.Boleto.Add(this);
						this._idVuelo = value.idVuelo;
					}
					else
					{
						this._idVuelo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Vuelo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rol")]
	public partial class Rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRol;
		
		private string _nombre;
		
		private EntitySet<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRolChanging(int value);
    partial void OnidRolChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public Rol()
		{
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					this.OnidRolChanging(value);
					this.SendPropertyChanging();
					this._idRol = value;
					this.SendPropertyChanged("idRol");
					this.OnidRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(128)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Usuario", Storage="_Usuario", ThisKey="idRol", OtherKey="idRol")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Rol = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoAsiento")]
	public partial class TipoAsiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipoAsiento;
		
		private string _nombre;
		
		private EntitySet<Asiento> _Asiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoAsientoChanging(int value);
    partial void OnidTipoAsientoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public TipoAsiento()
		{
			this._Asiento = new EntitySet<Asiento>(new Action<Asiento>(this.attach_Asiento), new Action<Asiento>(this.detach_Asiento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoAsiento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idTipoAsiento
		{
			get
			{
				return this._idTipoAsiento;
			}
			set
			{
				if ((this._idTipoAsiento != value))
				{
					this.OnidTipoAsientoChanging(value);
					this.SendPropertyChanging();
					this._idTipoAsiento = value;
					this.SendPropertyChanged("idTipoAsiento");
					this.OnidTipoAsientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(128)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoAsiento_Asiento", Storage="_Asiento", ThisKey="idTipoAsiento", OtherKey="idTipoAsiento")]
		public EntitySet<Asiento> Asiento
		{
			get
			{
				return this._Asiento;
			}
			set
			{
				this._Asiento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asiento(Asiento entity)
		{
			this.SendPropertyChanging();
			entity.TipoAsiento = this;
		}
		
		private void detach_Asiento(Asiento entity)
		{
			this.SendPropertyChanging();
			entity.TipoAsiento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuario;
		
		private string _nombreUsuario;
		
		private string _pass;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _email;
		
		private string _foto;
		
		private System.Nullable<int> _idRol;
		
		private EntityRef<Rol> _Rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnnombreUsuarioChanging(string value);
    partial void OnnombreUsuarioChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnfotoChanging(string value);
    partial void OnfotoChanged();
    partial void OnidRolChanging(System.Nullable<int> value);
    partial void OnidRolChanged();
    #endregion
		
		public Usuario()
		{
			this._Rol = default(EntityRef<Rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreUsuario", DbType="NVarChar(128)")]
		public string nombreUsuario
		{
			get
			{
				return this._nombreUsuario;
			}
			set
			{
				if ((this._nombreUsuario != value))
				{
					this.OnnombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._nombreUsuario = value;
					this.SendPropertyChanged("nombreUsuario");
					this.OnnombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="NVarChar(128)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(128)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="NVarChar(128)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(128)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="NVarChar(256)")]
		public string foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this.OnfotoChanging(value);
					this.SendPropertyChanging();
					this._foto = value;
					this.SendPropertyChanged("foto");
					this.OnfotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", DbType="Int")]
		public System.Nullable<int> idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					if (this._Rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRolChanging(value);
					this.SendPropertyChanging();
					this._idRol = value;
					this.SendPropertyChanged("idRol");
					this.OnidRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Usuario", Storage="_Rol", ThisKey="idRol", OtherKey="idRol", IsForeignKey=true)]
		public Rol Rol
		{
			get
			{
				return this._Rol.Entity;
			}
			set
			{
				Rol previousValue = this._Rol.Entity;
				if (((previousValue != value) 
							|| (this._Rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rol.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._Rol.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._idRol = value.idRol;
					}
					else
					{
						this._idRol = default(Nullable<int>);
					}
					this.SendPropertyChanged("Rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vuelo")]
	public partial class Vuelo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idVuelo;
		
		private string _horaVuelo;
		
		private string _destino;
		
		private string _estado;
		
		private string _fecha;
		
		private System.Nullable<int> _idAvion;
		
		private EntitySet<Boleto> _Boleto;
		
		private EntityRef<Avion> _Avion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidVueloChanging(int value);
    partial void OnidVueloChanged();
    partial void OnhoraVueloChanging(string value);
    partial void OnhoraVueloChanged();
    partial void OndestinoChanging(string value);
    partial void OndestinoChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnfechaChanging(string value);
    partial void OnfechaChanged();
    partial void OnidAvionChanging(System.Nullable<int> value);
    partial void OnidAvionChanged();
    #endregion
		
		public Vuelo()
		{
			this._Boleto = new EntitySet<Boleto>(new Action<Boleto>(this.attach_Boleto), new Action<Boleto>(this.detach_Boleto));
			this._Avion = default(EntityRef<Avion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVuelo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idVuelo
		{
			get
			{
				return this._idVuelo;
			}
			set
			{
				if ((this._idVuelo != value))
				{
					this.OnidVueloChanging(value);
					this.SendPropertyChanging();
					this._idVuelo = value;
					this.SendPropertyChanged("idVuelo");
					this.OnidVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horaVuelo", DbType="NVarChar(128)")]
		public string horaVuelo
		{
			get
			{
				return this._horaVuelo;
			}
			set
			{
				if ((this._horaVuelo != value))
				{
					this.OnhoraVueloChanging(value);
					this.SendPropertyChanging();
					this._horaVuelo = value;
					this.SendPropertyChanged("horaVuelo");
					this.OnhoraVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destino", DbType="NVarChar(128)")]
		public string destino
		{
			get
			{
				return this._destino;
			}
			set
			{
				if ((this._destino != value))
				{
					this.OndestinoChanging(value);
					this.SendPropertyChanging();
					this._destino = value;
					this.SendPropertyChanged("destino");
					this.OndestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(128)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="NVarChar(128)")]
		public string fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAvion", DbType="Int")]
		public System.Nullable<int> idAvion
		{
			get
			{
				return this._idAvion;
			}
			set
			{
				if ((this._idAvion != value))
				{
					if (this._Avion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidAvionChanging(value);
					this.SendPropertyChanging();
					this._idAvion = value;
					this.SendPropertyChanged("idAvion");
					this.OnidAvionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vuelo_Boleto", Storage="_Boleto", ThisKey="idVuelo", OtherKey="idVuelo")]
		public EntitySet<Boleto> Boleto
		{
			get
			{
				return this._Boleto;
			}
			set
			{
				this._Boleto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avion_Vuelo", Storage="_Avion", ThisKey="idAvion", OtherKey="idAvion", IsForeignKey=true)]
		public Avion Avion
		{
			get
			{
				return this._Avion.Entity;
			}
			set
			{
				Avion previousValue = this._Avion.Entity;
				if (((previousValue != value) 
							|| (this._Avion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Avion.Entity = null;
						previousValue.Vuelo.Remove(this);
					}
					this._Avion.Entity = value;
					if ((value != null))
					{
						value.Vuelo.Add(this);
						this._idAvion = value.idAvion;
					}
					else
					{
						this._idAvion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Avion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boleto(Boleto entity)
		{
			this.SendPropertyChanging();
			entity.Vuelo = this;
		}
		
		private void detach_Boleto(Boleto entity)
		{
			this.SendPropertyChanging();
			entity.Vuelo = null;
		}
	}
}
#pragma warning restore 1591
